# Generated by Django 5.0.7 on 2025-02-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0003_rename_name_review_reviewer_name_alter_review_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
