# Generated by Django 5.0.7 on 2025-02-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0008_alter_review_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedResearcher',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='review_images/avatar.png', upload_to='review_images/'),
        ),
    ]
