# Generated by Django 5.0.7 on 2025-02-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0009_delete_featuredresearcher_alter_review_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
