# Generated by Django 5.0.7 on 2025-02-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0010_alter_projects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsandevents',
            options={'verbose_name': 'News & Event', 'verbose_name_plural': 'News & Events'},
        ),
    ]
