# Generated by Django 5.0.7 on 2025-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0012_subscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
