# Generated by Django 5.0.7 on 2025-02-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0013_alter_paypalpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computing_Repo.paypalpayment'),
        ),
    ]
