# Generated by Django 5.0.7 on 2025-02-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0014_alter_paypalpayment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment',
        ),
    ]
