# Generated by Django 5.0.7 on 2025-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0015_remove_subscription_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
