# Generated by Django 5.0.7 on 2025-03-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0019_notificationssubscribedmembers_delete_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationsSubscribedMembers',
        ),
    ]
