# Generated by Django 5.0.7 on 2025-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0021_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
