# Generated by Django 5.0.7 on 2025-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0022_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Update Subscriber',
                'verbose_name_plural': 'Update Subscribers',
            },
        ),
    ]
