# Generated by Django 5.0.7 on 2025-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0023_updatesubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True),
        ),
    ]
