# Generated by Django 5.0.7 on 2025-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0024_projects_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='pricing',
        ),
        migrations.AddField(
            model_name='projects',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
