# Generated by Django 5.0.7 on 2025-04-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0027_flutterwavepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlutterwavePayment',
        ),
    ]
