# Generated by Django 5.0.7 on 2025-04-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computing_Repo', '0029_ipaypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpayPayment',
        ),
    ]
